### ISSUE TITLE
couldn't find "libsystemimage.so"

### ISSUE THREAD

**Issue by laonayan** [akwasnie/flir-android#1]
what is the problem?

`
2020-04-12 11:28:15.844 25698-25698/com.example.ala.glassescameraviewer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ala.glassescameraviewer, PID: 25698
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.ala.glassescameraviewer-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.ala.glassescameraviewer-1/lib/arm64, /data/app/com.example.ala.glassescameraviewer-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libsystemimage.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:972)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.flir.flironesdk.FrameProcessor.<clinit>(FrameProcessor.java:27)
        at com.example.ala.glassescameraviewer.MainActivity.onCreate(MainActivity.java:264)
        at android.app.Activity.performCreate(Activity.java:6758)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
`

**Comment by HuaiAnGG** [comment]
> what is the problem?
> 
> `2020-04-12 11:28:15.844 25698-25698/com.example.ala.glassescameraviewer E/AndroidRuntime: FATAL EXCEPTION: main Process: com.example.ala.glassescameraviewer, PID: 25698 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.ala.glassescameraviewer-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.ala.glassescameraviewer-1/lib/arm64, /data/app/com.example.ala.glassescameraviewer-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libsystemimage.so" at java.lang.Runtime.loadLibrary0(Runtime.java:972) at java.lang.System.loadLibrary(System.java:1530) at com.flir.flironesdk.FrameProcessor.<clinit>(FrameProcessor.java:27) at com.example.ala.glassescameraviewer.MainActivity.onCreate(MainActivity.java:264) at android.app.Activity.performCreate(Activity.java:6758) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918) at android.app.ActivityThread.-wrap12(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628) at android.os.Handler.dispatchMessage(Handler.java:110) at android.os.Looper.loop(Looper.java:203) at android.app.ActivityThread.main(ActivityThread.java:6406) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)`

**Comment by HuaiAnGG** [comment]
> what is the problem?
> 
> `2020-04-12 11:28:15.844 25698-25698/com.example.ala.glassescameraviewer E/AndroidRuntime: FATAL EXCEPTION: main Process: com.example.ala.glassescameraviewer, PID: 25698 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.ala.glassescameraviewer-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.ala.glassescameraviewer-1/lib/arm64, /data/app/com.example.ala.glassescameraviewer-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libsystemimage.so" at java.lang.Runtime.loadLibrary0(Runtime.java:972) at java.lang.System.loadLibrary(System.java:1530) at com.flir.flironesdk.FrameProcessor.<clinit>(FrameProcessor.java:27) at com.example.ala.glassescameraviewer.MainActivity.onCreate(MainActivity.java:264) at android.app.Activity.performCreate(Activity.java:6758) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918) at android.app.ActivityThread.-wrap12(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628) at android.os.Handler.dispatchMessage(Handler.java:110) at android.os.Looper.loop(Looper.java:203) at android.app.ActivityThread.main(ActivityThread.java:6406) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)`

**Comment by Maverick7** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.flir.flironeexampleapplication-k__qe9IV2BMg71-QXbx7_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.flir.flironeexampleapplication-k__qe9IV2BMg71-QXbx7_w==/lib/x86, /data/app/com.flir.flironeexampleapplication-k__qe9IV2BMg71-QXbx7_w==/base.apk!/lib/x86, /system/lib]]] couldn't find "libsystemimage.so"

**Comment by Maverick7** [comment]
same Issue, tried to remove x64 libs in jniLibs folder, but still throws this error

**Comment by RohankumarM** [comment]
Paste this in your build.gradle folder.

**android{
     defaultConfig{

                      ndk.abiFilters 'armeabi-v7a'
        }
}**
